### ISSUE TITLE
order status

### ISSUE THREAD

**Issue by merlinoa** [powwater/vendor_dashboard#47]
- change "status" column to "delivery_status"
    - this column will be either "pending", "awaiting delivery", "out for deliver", "delivered", etc.  All possible delivery status.
- create 2 new columns:
    - "vendor_response" type TEXT - this column will be either NA, accepted, or rejected, but we may need other options in the future, so do not restrict it in db.
    - "vendor_response_text" type TEXT - if the vendor response is to reject the order, then the vendor's reasoning for rejecting the order must be stored in this column
 - create a value box above the orders table that show the total number of NA (i.e. "Awaiting Vendor Response") orders

**Comment by jimbrig** [comment]
related to #37 as well

**Comment by jimbrig** [comment]
@merlinoa see #49 PR for review - for next actions I think we should add a couple more value boxes or at least discuss UI for this tab as the table shows a lot of information now.

**Comment by merlinoa** [comment]
I can't sign in with the most recent version ("main" or "develop" branch) of powpolished.  phone and email give me a not invited modal, Google sign in crashes the app with an error, and facebook sign in says it is not configured.
