### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by merlinoa** [powwater/vendor_dashboard#51]
I can't sign in with the most recent version ("main" or "develop" branch) of powpolished. phone and email give me a not invited modal, Google sign in crashes the app with an error, and facebook sign in says it is not configured.

Please just do phone or email sign in for now.  Do not spend any more time on powpolished.  I want to review powpolished first.  If powpolished is not working then use polished with just email for now.

**Comment by jimbrig** [comment]
@merlinoa deployed with polished - https://vendorsdashboard.powwater.org/?
