### ISSUE TITLE
implement a shiny reactivePoll function for checking db for updates and refreshing data

### ISSUE THREAD

**Issue by jimbrig** [powwater/vendor_dashboard#61]
See https://shiny.rstudio.com/reference/shiny/latest/reactivePoll.html

**Comment by jimbrig** [comment]
Let's check every 5 minutes

**Comment by jimbrig** [comment]
## Initial Attempt

I was not able to get this to work properly with reactivePoll yet. My initial attempt was using this approach:

```
session$userData$orders_trigger <- reactiveVal(0)

check_db_change <- reactivePoll(intervalMillis = 5 * 60 * 1000,
                                session = session,
                                checkFunc = function() {
                                  hold <- conn %>% tbl("orders")
                                  mod_stamp <- hold %>% pull(modified_at) %>% max(na.rm = TRUE)
                                  num_rows <- hold %>% pull(uid) %>% length()
                                  list(mod_stamp, num_rows)
                                },
                                valueFunc = function() {
                                  session$userData$orders_trigger() + 1
                                })

observeEvent(check_db_change(), {
  req(check_db_change() > 0)
  shinyjs::show("reload_bttn")
})

observeEvent(input$reload_bttn, {
  # trigger orders to reload database table
  session$userData$orders_trigger(check_db_change())
  
  # hide reload button
  shinyjs::hide("reload_bttn")
})
```

Which essentially does the following:

1. Using the `reactivePoll`'s `checkFunc`, check the orders table from the database every 5 minutes for any updates/changes to either the number of rows or the max of the modified_at dates and if any changes are detected:
2. Run the `valueFunc` which returns the current value of the `session$userData$orders_trigger()` + 1 into the `check_db_change()` reactive.
3. Observe `check_db_change` and display the UI's `reload_bttn` and a toast notification when changes are detected.
4. Observe the reload_bttn, if clicked update the `session$userData$orders_trigger` by 1 which should re-trigger the orders table to re-load from the database. 

From debugging it seemed the issue was with observing the `check_db_change()` reactive's `valueFunc`'s return when it gets triggered. Couldn't get this to work with the current setup so I tried a couple of alternatives which didn't work either - seems like the `reactivePoll` is not as simple as say an `eventReactive`. 

## Reference

- Initial attempt using reactivePoll was drawn from [the function's man page here](https://shiny.rstudio.com/reference/shiny/latest/reactivePoll.html) - however their example re-loads the entire dataset as opposed to an intermediate step involving a reload button.

- Could also try a simpler approach with a reactive and `invalidateLater()` instead of the `reactivePoll`

- Another potential resource I found was [shiny-auto-refresh](https://github.com/colearendt/shiny-auto-refresh/blob/master/app.R) which uses JavaScript to set a timeout for reloading the page.

**Comment by jimbrig** [comment]
@merlinoa 
Going to put this on hold for now as other issues are higher priority and will circle back. I pushed the latest code into the [feature/reactivePoll branch's orders_module.R](https://github.com/powwater/vendor_dashboard/blob/feature/reactivePoll/shiny_app/R/2_orders_module.R)

**Comment by merlinoa** [comment]
@jimbrig I made 2 commits to this branch

1. was to create unique error messages for the database queries.  The point of the messages is so we can quickly identify the query that is throwing the error.  If all queries have the same error message then the messages are not very helpful.  Please update this on admin portal as well.

2.  Fixed the reactive trigger you were using.  We only need the session$userData$orders_trigger().  Creating this other trigger is not necessary, and it was not working properly either.  

I am now getting an error in the customers GET query, and the app is unable to get past the loading screen because of this error.  Please fix this error, and take a look at the new reactivePoll.  Attempt to finish the reactivePoll, and send back to me to review after you finish or get stuck.

**Comment by jimbrig** [comment]
@merlinoa thanks, taking a look now.

**Comment by jimbrig** [comment]
@merlinoa I updated the code and it runs fine now - however I am seeing the same issues I was having with the reactivePoll where it detects a database change but does not trigger the `orders()` reactive to reload. 

![image](https://user-images.githubusercontent.com/32652297/114615290-7f8c3800-9c73-11eb-82a0-b47d19d33617.png)

But the app stays in the same state.

Additionally, with this setup, the data will update whenever a change to the database is detected as opposed to allowing the user to click a reload data button that appears when a change is detected (see my most recent commit where I comment out that code).

**Comment by merlinoa** [comment]
@jimbrig FYI -- I created a PR to fix that googleway bug.  Until it gets fixed/merged, you can install from remotes::install_version("merlinoa/googleway")

**Comment by jimbrig** [comment]
good deal, thanks.

**Comment by jimbrig** [comment]
@merlinoa do you have any updates for the reactivePoll issue / want me to try again?

**Comment by merlinoa** [comment]
@jimbrig working on it now

**Comment by merlinoa** [comment]
Reactive poll should be in good shape now.  Please verify that it is working properly, and then you can merge.

**Comment by jimbrig** [comment]
Verified. Made PR #79 and will merge into develop and once i finish the steps below we can merge dev into main and re-deploy. Thanks @merlinoa !

***

From PR #79:

First version of the reactive-polling to the database for reloading data tables when changes are detected. 

This is how it currently looks:

Disabled:

![image](https://user-images.githubusercontent.com/32652297/114931740-9e6e0400-9e04-11eb-8232-eef27e6a9470.png)


Enabled:

![image](https://user-images.githubusercontent.com/32652297/114931794-b34a9780-9e04-11eb-8177-06d1fcc1eeaa.png)

Change from R console to last modified date:

![image](https://user-images.githubusercontent.com/32652297/114931880-d412ed00-9e04-11eb-9f58-298f55f64789.png)

***

Next steps are to:

- [ ] agree upon code and UI for the reload button and change detection

*Note: a better alternative to the modified date/row numbers as a proxy to determine changes would be using the PostgreSQL `pg_last_committed_xact()` timestamp.*

```
mod_stamp <- RPostgres::dbGetQuery(conn, "SELECT timestamp FROM pg_last_committed_xact()")
```
- [ ] implement this across all modules with data tables
- [ ] implement in adminportal app
